app1/urls.py
from django.urls import path
from app1.views import *
app_name='honey'
urlpatterns=[
    path('honey/',honey,name='honey'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='vinny'
urlpatterns=[
    path('vinny/',vinny,name='vinny'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def honey(request):
    return render(request,'honey.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def vinny(request):
    return render(request,'vinny.html')

templates/honey.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HI I AM HONEY</h1>
    <h2>
        <a href="{% url 'vinny:vinny' %}"> click go to vinny page</a>
    </h2>
</body>
</html>

templates/vinny.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>MY SISTER IS VINNY</h1>
    <h2>
        <a href="{% url 'honey:honey' %}">click to go honey page</a>
    </h2>
</body>
</html>